#!/usr/bin/python3
#SPDX-FileCopyrightText: 2022 Nakayama Nanami
#SPDX-License-Identifier: BSD-3-Clause

import sys

ans = 0

for line in sys.stdin:
    if int(line) >= 0 :
        try:
            ans += int(line)
        except:
            ans += float(line)
    else:
        try:
            ans -= int(line)
        except:
            ans -= float(line)

print(ans)
