#!/usr/bin/python3
#SPDX-FileCopyrightText: 2022 Nakayama Nanami
#SPDX-License-Identifier: BSD-3-Clause
import sys

ans = 0.0
for line in sys.stdin:
    ans +=float(line)

print(ans)

このソフトウェアパッケージは，3条項BSDライセンスの下，再頒布および使用が許可されます．
  * © 2022 Nakayama Nanami]
